services:
  docker_24.04:
    build:
      context: ./24.04

    volumes:
      - /home/qwerty/ctf:/home/qwerty/ctf

    network_mode: "host"

    privileged: true 

    entrypoint: ["tail", "-f", "/dev/null"]

  docker_22.04:
    build:
      context: ./22.04
      
    volumes:
      - /home/qwerty/ctf:/home/qwerty/ctf

    network_mode: "host"

    privileged: true 

    entrypoint: ["tail", "-f", "/dev/null"]
  